// Application icon vocabulary. Keep plugin names compatible; prefer filled, rounded shapes.
export * from '@mui/icons-material'
export {
  CenterFocusStrongRounded as CenterFocusStrong, RestoreRounded as Restore, DeleteForeverRounded as DeleteForever,
  CheckCircleRounded as CheckCircle, CloseRounded as Close, ExpandMoreRounded as ExpandMore,
  ChevronRightRounded as ChevronRight, ErrorRounded as ErrorOutline, CheckRounded as Check,
  InfoRounded as Info, ChecklistRounded as Checklist, LaunchRounded as Launch,
  DragIndicatorRounded as DragIndicator, AddRounded as Add, EditNoteRounded as EditNote,
  SendRounded as Send, StopRounded as Stop, SearchRounded as Search,
  ImageRounded as Image, MenuBookRounded as MenuBook, EditRounded as Edit,
  PsychologyRounded as Psychology, ScheduleRounded as Schedule, ClearRounded as Clear,
  ChevronLeftRounded as ChevronLeft, ContentCopyRounded as ContentCopy, SwapHorizRounded as SwapHoriz,
  RefreshRounded as Refresh, ZoomInRounded as ZoomIn, ZoomOutRounded as ZoomOut,
  RepeatRounded as Repeat, AccessTimeRounded as AccessTime, AddTaskRounded as AddTask,
  AttachFileRounded as AttachFile, DeleteRounded as DeleteOutline, KeyboardVoiceRounded as KeyboardVoice,
  LabelImportantRounded as LabelImportantOutline, NotesRounded as Notes, OpenInNewRounded as OpenInNew,
  PriorityHighRounded as PriorityHigh, RadioButtonUncheckedRounded as RadioButtonUnchecked, VisibilityRounded as Visibility,
  DeleteRounded as Delete, SelectAllRounded as SelectAll, MoreVertRounded as MoreVert,
  WebAssetRounded as WebAsset, CategoryRounded as Category, HistoryRounded as History,
  CheckBoxOutlineBlankRounded as CheckBoxOutlineBlank, MoreHorizRounded as MoreHoriz, ExpandLessRounded as ExpandLess,
  CheckCircleRounded as CheckCircleOutline, UndoRounded, DeleteRounded as DeleteOutlineRounded,
  ChecklistRounded, WarningRounded as Warning, FlagRounded as Flag,
  SortRounded as Sort, CircleRounded as Circle, CheckRounded,
  CloseRounded, OpenInNewRounded, SnoozeRounded,
  CheckCircleRounded, ExpandMoreRounded, RadioButtonUncheckedRounded,
  CloudRounded as Cloud, CloudDoneRounded as CloudDone, CloudOffRounded as CloudOff,
  SyncRounded as Sync, PlayArrowRounded as PlayArrow, PauseRounded as Pause,
  TaskAltRounded as TaskAlt, ListRounded as List, CloudDownloadRounded,
  DeleteRounded, PowerSettingsNewRounded, RocketLaunchRounded,
  ErrorRounded as Error, TuneRounded as Tune, OpenInFullRounded,
  PauseRounded, PlayArrowRounded, CloudSyncRounded as CloudSync,
  CloudRounded as CloudQueue, VisibilityOffRounded as VisibilityOff, HelpRounded as HelpOutline,
  LogoutRounded as Logout, FolderOpenRounded, NoteAddRounded as NoteAdd,
  DashboardRounded as Dashboard, RefreshRounded, Google,
  LinkOffRounded as LinkOff, CloudUploadRounded as CloudUpload, CloudDownloadRounded as CloudDownload,
  MicRounded as Mic, ComputerRounded as Computer, CompareArrowsRounded as CompareArrows,
  LinkRounded as Link, VerticalAlignTopRounded as VerticalAlignTop, VerticalAlignBottomRounded as VerticalAlignBottom,
  ClearAllRounded as ClearAll, ArrowBackRounded as ArrowBack, PaletteRounded as Palette,
  GetAppRounded as GetApp, KeyboardRounded as Keyboard, MemoryRounded as Memory,
  WifiRounded as Wifi, CodeRounded as Code, RestartAltRounded as RestartAlt,
  ContentPasteRounded as ContentPaste, CleaningServicesRounded as CleaningServices, FilterListRounded as FilterList,
  WavingHandRounded as WavingHand, DownloadRounded as Download, StorageRounded as Storage,
  GraphicEqRounded as GraphicEq, FormatBoldRounded as FormatBold, FormatItalicRounded as FormatItalic,
  FormatStrikethroughRounded as FormatStrikethrough, FormatListBulletedRounded as FormatListBulleted, FormatListNumberedRounded as FormatListNumbered,
  FormatQuoteRounded as FormatQuote, TableChartRounded as TableChart, ViewColumnRounded as ViewColumn,
  HighlightRounded as Highlight, TipsAndUpdatesRounded as TipsAndUpdates, HorizontalRuleRounded as HorizontalRule,
  FormatClearRounded as FormatClear, ArrowDropDownRounded as ArrowDropDown, AutoFixHighRounded as AutoFixHigh,
  SummarizeRounded as Summarize, TranslateRounded as Translate, ChatRounded as Chat,
  InsertLinkRounded as InsertLink, DataObjectRounded as DataObject, EmailRounded as Email,
  WifiOffRounded as WifiOff, Brightness4Rounded as Brightness4, Brightness7Rounded as Brightness7,
  AccountCircle, Person, PhotoCameraRounded as PhotoCamera, LanguageRounded as Language,
  ArrowOutwardRounded as ArrowOutward, AutorenewRounded as Autorenew, AutoModeRounded as AutoMode,
  ExploreRounded as Explore, InfoRounded as InfoOutlined, FullscreenRounded as Fullscreen,
  FullscreenExitRounded as FullscreenExit, KeyboardArrowUpRounded as KeyboardArrowUp, KeyboardArrowDownRounded as KeyboardArrowDown,
  VisibilityRounded, VisibilityOffRounded, TrendingUpRounded as TrendingUp,
  SubjectRounded as Subject, BookmarkRounded as BookmarkBorder, TextSnippetRounded as TextSnippet,
  ShuffleRounded, ManageSearchRounded as ManageSearch, FlashOnRounded as FlashOn,
  RecordVoiceOverRounded as RecordVoiceOver,
} from '@mui/icons-material'
export {
  FlotaNoteIcon as Article, FlotaNoteIcon as Description, FlotaNoteIcon as DescriptionOutlined,
  FlotaNoteIcon as Note, FlotaNoteIcon as NoteAlt, FlotaNoteIcon as StickyNote2,
  FlotaTodoIcon as CheckBox, FlotaCalendarIcon as CalendarToday, FlotaCalendarIcon as CalendarMonth,
  FlotaCalendarIcon as Today, FlotaTimelineIcon as Timeline, FlotaWhiteboardIcon as Brush,
  FlotaSparkleIcon as AutoAwesome, FlotaPluginIcon as Extension, FlotaPluginIcon as ExtensionRounded,
  FlotaSettingsIcon as Settings, FlotaPinIcon as PushPin,
  FlotaPinIcon as PushPinOutlined, FlotaTagIcon as Label, FlotaTagIcon as LocalOffer,
  FlotaTagIcon as Tag, FlotaGraphIcon as Hub,
} from './FlotaIcons'
